# diabetes project

# imported lib

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import seaborn as sns
from sklearn.metrics import mean_squared_error , r2_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import numpy as np

# load, split, clean the data

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/hanalareina29/Diabetes.csv/refs/heads/main/diabetes.csv')

#remove rows that contain zero in this coloumns
columns = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df = df.loc[(df[columns] != 0).all(axis=1)]

## re split after cleaning
y = df['Outcome']
x = df.drop('Outcome', axis=1)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=10)

## datd info

In [3]:
print(df.shape)
print(df.info())
df.describe()

(392, 9)
<class 'pandas.core.frame.DataFrame'>
Index: 392 entries, 3 to 765
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               392 non-null    int64
 1   Glucose                   392 non-null    int64
 2   BloodPressure             392 non-null    int64
 3   SkinThickness             392 non-null    int64
 4   Insulin                   392 non-null    int64
 5   BMI                       392 non-null    float64
 6   DiabetesPedigreeFunction  392 non-null    float64
 7   Age                       392 non-null    int64
 8   Outcome                   392 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 30.6 KB
None

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000
mean,3.301020,122.627551,70.663265,29.145408,156.056122,33.086224,0.523046,30.864796,0.331633
std,3.211424,30.860781,12.496092,10.516424,118.841690,7.027659,0.345488,10.200777,0.471401
min,0.000000,56.000000,24.000000,7.000000,14.000000,18.200000,0.085000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,21.000000,76.750000,28.400000,0.269750,23.000000,0.000000
50%,2.000000,119.000000,70.000000,29.000000,125.500000,33.200000,0.449500,27.000000,0.000000
75%,5.000000,143.000000,78.000000,37.000000,190.000000,37.100000,0.687000,36.000000,1.000000
max,17.000000,198.000000,110.000000,63.000000,846.000000,67.100000,2.420000,81.000000,1.000000

# Feature scalling or standersation

In [4]:
scaler= StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

# bulding model

## training model

In [5]:
logr = LogisticRegression()
logr.fit(x_train, y_train)

LogisticRegression()

## applying model

In [6]:
y_logr_train_pred = logr.predict(x_train)
y_logr_test_pred = logr.predict(x_test)

## evaluate model

In [7]:
logr_train_mse = mean_squared_error(y_train, y_logr_train_pred)
logr_train_r2 = r2_score(y_train , y_logr_train_pred)

logr_test_mse = mean_squared_error(y_test, y_logr_test_pred)
logr_test_r2 = r2_score(y_test , y_logr_test_pred)

logr_results = pd.DataFrame(['LogisticRegression' 
, logr_train_mse , logr_train_r2, logr_test_mse ,logr_test_r2]).transpose()
logr_results.columns = ['methods', 'training mse', 'training r2', 'test mse', 'test r2']
logr_results

              methods training mse training r2  test mse   test r2
0  LogisticRegression     0.210863    0.062789  0.253165 -0.226708

# test

In [8]:
x_train_prediction = logr.predict(x_train)
training_data_accuracy = accuracy_score(x_train_prediction, y_train)

print('Accuracy score of the training data : ', training_data_accuracy)

Accuracy score of the training data :  0.7891373801916933

In [9]:
input_data = (1,90,66,23,94,28.1,0.167,21)

# changing the input_data to numpy array
input_data_nparray = np.asarray(input_data)

# reshape the array as we are predicting for one instance
input_data_reshaped = input_data_nparray.reshape(1,-1)

# standardize the input data
std_data = scaler.transform(input_data_reshaped)
print(std_data)

prediction = logr.predict(std_data)

if (prediction[0] == 0):
  print('The person is not diabetic')
else:
  print('The person is diabetic')

[[-0.71038668 -1.07643893 -0.35543382 -0.57604733 -0.53461054 -0.7105676
  -1.04886421 -0.96592407]]
The person is not diabetic

D:\program\anaconda\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(